# Generated by Django 4.1.2 on 2022-12-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitychatroommember',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='communitychatroommessage',
            old_name='user',
            new_name='owner',
        ),
    ]
