# Generated by Django 4.1.2 on 2022-12-26 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_rename_user_communitychatroommember_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitychatroommember',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communitychatroommember',
            name='is_typing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='communitychatroom',
            name='slug',
            field=models.SlugField(default='9da1e054-f570-46', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='communitychatroommember',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
