# Generated by Django 4.1.2 on 2022-12-26 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('chat', '0003_communitychatroommember_is_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitychatroom',
            name='community',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='community.community'),
        ),
        migrations.AlterField(
            model_name='communitychatroom',
            name='slug',
            field=models.SlugField(default='f8f5388c-f5a9-43', max_length=255, unique=True),
        ),
    ]
