# Generated by Django 4.1.2 on 2022-12-26 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_alter_communitychatroom_community_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitychatroom',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='communitychatroommember',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
