# Generated by Django 4.1.2 on 2022-12-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_communitychatroom_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitychatroommember',
            old_name='owner',
            new_name='member',
        ),
    ]
