# Generated by Django 4.1.2 on 2022-12-25 05:17

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='community_logos'),
        ),
    ]
